# Generated by Django 4.1.5 on 2023-04-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('due_to', models.DateField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
